- doctrine/migrations/issues/173
- 1up-lab/OneupUploaderBundle/issues/114
- sensiolabs/SensioGeneratorBundle/issues/280
- dustin10/VichUploaderBundle/issues/273
# - sensiolabs/SensioGeneratorBundle/issues/285
- symfony/symfony/issues/11287
- sensiolabs/SensioGeneratorBundle/issues/287
